---
name: default
server: 
  ip: localhost
  port: 7890
channels: 
  - 
    index: 0
    pixels: 0
    type: 
    colorspace: 
  - 
    index: 1
    pixels: 0
    type: 
    colorspace: 
  - 
    index: 2
    pixels: 0
    type: 
    colorspace: 
  - 
    index: 3
    pixels: 0
    type: 
    colorspace: 
  - 
    index: 4
    pixels: 0
    type: 
    colorspace: 
  - 
    index: 5
    pixels: 0
    type: 
    colorspace: 
  - 
    index: 6
    pixels: 0
    type: 
    colorspace: 
  - 
    index: 7
    pixels: 0
    type: 
    colorspace: 
  - 
    index: 8
    pixels: 64
    type: strip
    colorspace: RGB
  - 
    index: 9
    pixels: 55
    type: strip
    colorspace: RGB
  - 
    index: 10
    pixels: 22
    type: strip
    colorspace: RGB
  - 
    index: 11
    pixels: 37
    type: strip
    colorspace: RGB
  - 
    index: 12
    pixels: 50
    type: strand
    colorspace: GRB  
  - 
    index: 13
    pixels: 50
    type: strand
    colorspace: GRB 
  - 
    index: 14
    pixels: 22
    type: strand
    colorspace: GRB
  - 
    index: 15
    pixels: 0
    type: 
    colorspace: 
letters:
  -
    index: 0
    character: G
    channels: []
    width: 0
    height: 0
    loops: []
  - 
    index: 1
    character: L 
    channels: 
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
    width: 115
    height: 178
    loops: 
      -
        -
          channel: 8
          pixel: 0
        -
          channel: 11
          pixel: 36
        -
          channel: 10
          pixel: 0
        -
          channel: 9
          pixel: 54
  - 
    index: 2
    character: A
    channels: []
    width: 0
    height: 0
    loops: []
  - 
    index: 3
    character: M 
    channels: []
    width: 0
    height: 0
    loops: []
  - 
    index: 4
    character: C 
    channels: []
    width: 0
    height: 0
    loops: []
  - 
    index: 5
    character: O 
    channels: []
    width: 0
    height: 0
    loops: []
  - 
    index: 6
    character: C 
    channels: []
    width: 0
    height: 0
    loops: []
  - 
    index: 7
    character: K 
    channels: []
    width: 0
    height: 0
    loops: []
  - 
    index: 8
    character: S 
    channels: []
    width: 8
    height: 12
    loops: []
pixels: 
  - 
    - 8
    - 0
    - 0.13
    - 0.5
  - 
    - 8
    - 1
    - 0.148
    - 0.509
  - 
    - 8
    - 2
    - 0.164
    - 0.517
  - 
    - 8
    - 3
    - 0.177
    - 0.527
  - 
    - 8
    - 4
    - 0.191
    - 0.537
  - 
    - 8
    - 5
    - 0.202
    - 0.547
  - 
    - 8
    - 6
    - 0.211
    - 0.558
  - 
    - 8
    - 7
    - 0.218
    - 0.569
  - 
    - 8
    - 8
    - 0.225
    - 0.58
  - 
    - 8
    - 9
    - 0.232
    - 0.59
  - 
    - 8
    - 10
    - 0.239
    - 0.6
  - 
    - 8
    - 11
    - 0.244
    - 0.611
  - 
    - 8
    - 12
    - 0.255
    - 0.621
  - 
    - 8
    - 13
    - 0.259
    - 0.632
  - 
    - 8
    - 14
    - 0.264
    - 0.642
  - 
    - 8
    - 15
    - 0.266
    - 0.653
  - 
    - 8
    - 16
    - 0.268
    - 0.664
  - 
    - 8
    - 17
    - 0.27
    - 0.675
  - 
    - 8
    - 18
    - 0.273
    - 0.685
  - 
    - 8
    - 19
    - 0.273
    - 0.695
  - 
    - 8
    - 20
    - 0.273
    - 0.706
  - 
    - 8
    - 21
    - 0.273
    - 0.716
  - 
    - 8
    - 22
    - 0.273
    - 0.725
  - 
    - 8
    - 23
    - 0.273
    - 0.736
  - 
    - 8
    - 24
    - 0.27
    - 0.747
  - 
    - 8
    - 25
    - 0.266
    - 0.757
  - 
    - 8
    - 26
    - 0.261
    - 0.767
  - 
    - 8
    - 27
    - 0.259
    - 0.777
  - 
    - 8
    - 28
    - 0.257
    - 0.788
  - 
    - 8
    - 29
    - 0.253
    - 0.798
  - 
    - 8
    - 30
    - 0.257
    - 0.808
  - 
    - 8
    - 31
    - 0.248
    - 0.818
  - 
    - 8
    - 32
    - 0.243
    - 0.828
  - 
    - 8
    - 33
    - 0.237
    - 0.839
  - 
    - 8
    - 34
    - 0.239
    - 0.85
  - 
    - 8
    - 35
    - 0.234
    - 0.86
  - 
    - 8
    - 36
    - 0.228
    - 0.87
  - 
    - 8
    - 37
    - 0.223
    - 0.88
  - 
    - 8
    - 38
    - 0.216
    - 0.891
  - 
    - 8
    - 39
    - 0.21
    - 0.9
  - 
    - 8
    - 40
    - 0.204
    - 0.911
  - 
    - 8
    - 41
    - 0.192
    - 0.92
  - 
    - 8
    - 42
    - 0.183
    - 0.93
  - 
    - 8
    - 43
    - 0.17
    - 0.939
  - 
    - 8
    - 44
    - 0.161
    - 0.948
  - 
    - 8
    - 45
    - 0.15
    - 0.958
  - 
    - 8
    - 46
    - 0.139
    - 0.969
  - 
    - 8
    - 47
    - 0.13
    - 0.978
  - 
    - 8
    - 48
    - 0.116
    - 0.987
  - 
    - 8
    - 49
    - 0.13
    - 0.986
  - 
    - 8
    - 50
    - 0.15
    - 0.98
  - 
    - 8
    - 51
    - 0.175
    - 0.975
  - 
    - 8
    - 52
    - 0.2
    - 0.969
  - 
    - 8
    - 53
    - 0.225
    - 0.965
  - 
    - 8
    - 54
    - 0.252
    - 0.961
  - 
    - 8
    - 55
    - 0.275
    - 0.958
  - 
    - 8
    - 56
    - 0.301
    - 0.955
  - 
    - 8
    - 57
    - 0.33
    - 0.953
  - 
    - 8
    - 58
    - 0.359
    - 0.953
  - 
    - 8
    - 59
    - 0.386
    - 0.953
  - 
    - 8
    - 60
    - 0.414
    - 0.955
  - 
    - 8
    - 61
    - 0.443
    - 0.955
  - 
    - 8
    - 62
    - 0.47
    - 0.957
  - 
    - 8
    - 63
    - 0.494
    - 0.959
  - 
    - 9
    - 0
    - 0.134
    - 0.492
  - 
    - 9
    - 1
    - 0.161
    - 0.494
  - 
    - 9
    - 2
    - 0.191
    - 0.496
  - 
    - 9
    - 3
    - 0.222
    - 0.498
  - 
    - 9
    - 4
    - 0.248
    - 0.5
  - 
    - 9
    - 5
    - 0.275
    - 0.502
  - 
    - 9
    - 6
    - 0.307
    - 0.504
  - 
    - 9
    - 7
    - 0.334
    - 0.506
  - 
    - 9
    - 8
    - 0.362
    - 0.508
  - 
    - 9
    - 9
    - 0.39
    - 0.51
  - 
    - 9
    - 10
    - 0.416
    - 0.512
  - 
    - 9
    - 11
    - 0.446
    - 0.512
  - 
    - 9
    - 12
    - 0.475
    - 0.514
  - 
    - 9
    - 13
    - 0.504
    - 0.513
  - 
    - 9
    - 14
    - 0.532
    - 0.514
  - 
    - 9
    - 15
    - 0.559
    - 0.513
  - 
    - 9
    - 16
    - 0.591
    - 0.512
  - 
    - 9
    - 17
    - 0.618
    - 0.511
  - 
    - 9
    - 18
    - 0.645
    - 0.508
  - 
    - 9
    - 19
    - 0.673
    - 0.504
  - 
    - 9
    - 20
    - 0.7
    - 0.502
  - 
    - 9
    - 21
    - 0.732
    - 0.498
  - 
    - 9
    - 22
    - 0.755
    - 0.492
  - 
    - 9
    - 23
    - 0.782
    - 0.488
  - 
    - 9
    - 24
    - 0.811
    - 0.484
  - 
    - 9
    - 25
    - 0.836
    - 0.48
  - 
    - 9
    - 26
    - 0.866
    - 0.474
  - 
    - 9
    - 27
    - 0.891
    - 0.468
  - 
    - 9
    - 28
    - 0.92
    - 0.464
  - 
    - 9
    - 29
    - 0.945
    - 0.458
  - 
    - 9
    - 30
    - 0.943
    - 0.467
  - 
    - 9
    - 31
    - 0.927
    - 0.477
  - 
    - 9
    - 32
    - 0.918
    - 0.488
  - 
    - 9
    - 33
    - 0.909
    - 0.498
  - 
    - 9
    - 34
    - 0.9
    - 0.51
  - 
    - 9
    - 35
    - 0.889
    - 0.52
  - 
    - 9
    - 36
    - 0.884
    - 0.531
  - 
    - 9
    - 37
    - 0.88
    - 0.542
  - 
    - 9
    - 38
    - 0.876
    - 0.553
  - 
    - 9
    - 39
    - 0.873
    - 0.564
  - 
    - 9
    - 40
    - 0.875
    - 0.575
  - 
    - 9
    - 41
    - 0.873
    - 0.586
  - 
    - 9
    - 42
    - 0.875
    - 0.597
  - 
    - 9
    - 43
    - 0.876
    - 0.607
  - 
    - 9
    - 44
    - 0.88
    - 0.619
  - 
    - 9
    - 45
    - 0.88
    - 0.63
  - 
    - 9
    - 46
    - 0.88
    - 0.64
  - 
    - 9
    - 47
    - 0.886
    - 0.653
  - 
    - 9
    - 48
    - 0.889
    - 0.66
  - 
    - 9
    - 49
    - 0.897
    - 0.671
  - 
    - 9
    - 50
    - 0.9
    - 0.682
  - 
    - 9
    - 51
    - 0.907
    - 0.692
  - 
    - 9
    - 52
    - 0.911
    - 0.703
  - 
    - 9
    - 53
    - 0.916
    - 0.713
  - 
    - 9
    - 54
    - 0.92
    - 0.723
  - 
    - 10
    - 0
    - 0.639
    - 0.603
  - 
    - 10
    - 1
    - 0.664
    - 0.608
  - 
    - 10
    - 2
    - 0.685
    - 0.613
  - 
    - 10
    - 3
    - 0.702
    - 0.621
  - 
    - 10
    - 4
    - 0.711
    - 0.631
  - 
    - 10
    - 5
    - 0.72
    - 0.642
  - 
    - 10
    - 6
    - 0.72
    - 0.653
  - 
    - 10
    - 7
    - 0.723
    - 0.664
  - 
    - 10
    - 8
    - 0.714
    - 0.673
  - 
    - 10
    - 9
    - 0.705
    - 0.683
  - 
    - 10
    - 10
    - 0.695
    - 0.692
  - 
    - 10
    - 11
    - 0.684
    - 0.703
  - 
    - 10
    - 12
    - 0.673
    - 0.712
  - 
    - 10
    - 13
    - 0.686
    - 0.714
  - 
    - 10
    - 14
    - 0.716
    - 0.711
  - 
    - 10
    - 15
    - 0.739
    - 0.709
  - 
    - 10
    - 16
    - 0.766
    - 0.709
  - 
    - 10
    - 17
    - 0.796
    - 0.709
  - 
    - 10
    - 18
    - 0.825
    - 0.711
  - 
    - 10
    - 19
    - 0.852
    - 0.714
  - 
    - 10
    - 20
    - 0.877
    - 0.718
  - 
    - 10
    - 21
    - 0.905
    - 0.723
  - 
    - 11
    - 0
    - 0.608
    - 0.602
  - 
    - 11
    - 1
    - 0.582
    - 0.608
  - 
    - 11
    - 2
    - 0.559
    - 0.614
  - 
    - 11
    - 3
    - 0.537
    - 0.62
  - 
    - 11
    - 4
    - 0.518
    - 0.627
  - 
    - 11
    - 5
    - 0.502
    - 0.636
  - 
    - 11
    - 6
    - 0.488
    - 0.645
  - 
    - 11
    - 7
    - 0.473
    - 0.655
  - 
    - 11
    - 8
    - 0.464
    - 0.664
  - 
    - 11
    - 9
    - 0.455
    - 0.675
  - 
    - 11
    - 10
    - 0.443
    - 0.684
  - 
    - 11
    - 11
    - 0.434
    - 0.694
  - 
    - 11
    - 12
    - 0.43
    - 0.704
  - 
    - 11
    - 13
    - 0.42
    - 0.714
  - 
    - 11
    - 14
    - 0.42
    - 0.725
  - 
    - 11
    - 15
    - 0.418
    - 0.735
  - 
    - 11
    - 16
    - 0.416
    - 0.747
  - 
    - 11
    - 17
    - 0.416
    - 0.755
  - 
    - 11
    - 18
    - 0.414
    - 0.765
  - 
    - 11
    - 19
    - 0.415
    - 0.776
  - 
    - 11
    - 20
    - 0.416
    - 0.786
  - 
    - 11
    - 21
    - 0.416
    - 0.797
  - 
    - 11
    - 22
    - 0.419
    - 0.807
  - 
    - 11
    - 23
    - 0.42
    - 0.816
  - 
    - 11
    - 24
    - 0.424
    - 0.828
  - 
    - 11
    - 25
    - 0.43
    - 0.836
  - 
    - 11
    - 26
    - 0.432
    - 0.848
  - 
    - 11
    - 27
    - 0.436
    - 0.858
  - 
    - 11
    - 28
    - 0.439
    - 0.869
  - 
    - 11
    - 29
    - 0.442
    - 0.878
  - 
    - 11
    - 30
    - 0.449
    - 0.889
  - 
    - 11
    - 31
    - 0.452
    - 0.9
  - 
    - 11
    - 32
    - 0.457
    - 0.909
  - 
    - 11
    - 33
    - 0.464
    - 0.919
  - 
    - 11
    - 34
    - 0.472
    - 0.93
  - 
    - 11
    - 35
    - 0.482
    - 0.939
  - 
    - 11
    - 36
    - 0.489
    - 0.949
  - 
    - 12
    - 0
    - 0.286
    - 0.66
  - 
    - 12
    - 1
    - 0.348
    - 0.661
  - 
    - 12
    - 2
    - 0.407
    - 0.662
  - 
    - 12
    - 3
    - 0.403
    - 0.686
  - 
    - 12
    - 4
    - 0.344
    - 0.684
  - 
    - 12
    - 5
    - 0.285
    - 0.683
  - 
    - 12
    - 6
    - 0.282
    - 0.704
  - 
    - 12
    - 7
    - 0.341
    - 0.706
  - 
    - 12
    - 8
    - 0.405
    - 0.708
  - 
    - 12
    - 9
    - 0.401
    - 0.73
  - 
    - 12
    - 10
    - 0.345
    - 0.728
  - 
    - 12
    - 11
    - 0.281
    - 0.726
  - 
    - 12
    - 12
    - 0.278
    - 0.75
  - 
    - 12
    - 13
    - 0.339
    - 0.75
  - 
    - 12
    - 14
    - 0.398
    - 0.752
  - 
    - 12
    - 15
    - 0.399
    - 0.773
  - 
    - 12
    - 16
    - 0.34
    - 0.772
  - 
    - 12
    - 17
    - 0.278
    - 0.771
  - 
    - 12
    - 18
    - 0.275
    - 0.793
  - 
    - 12
    - 19
    - 0.337
    - 0.793
  - 
    - 12
    - 20
    - 0.398
    - 0.795
  - 
    - 12
    - 21
    - 0.395
    - 0.817
  - 
    - 12
    - 22
    - 0.336
    - 0.815
  - 
    - 12
    - 23
    - 0.275
    - 0.814
  - 
    - 12
    - 24
    - 0.276
    - 0.836
  - 
    - 12
    - 25
    - 0.336
    - 0.837
  - 
    - 12
    - 26
    - 0.391
    - 0.838
  - 
    - 12
    - 27
    - 0.418
    - 0.858
  - 
    - 12
    - 28
    - 0.361
    - 0.855
  - 
    - 12
    - 29
    - 0.305
    - 0.854
  - 
    - 12
    - 30
    - 0.245
    - 0.854
  - 
    - 12
    - 31
    - 0.241
    - 0.875
  - 
    - 12
    - 32
    - 0.3
    - 0.876
  - 
    - 12
    - 33
    - 0.36
    - 0.878
  - 
    - 12
    - 34
    - 0.418
    - 0.879
  - 
    - 12
    - 35
    - 0.416
    - 0.9
  - 
    - 12
    - 36
    - 0.355
    - 0.898
  - 
    - 12
    - 37
    - 0.299
    - 0.899
  - 
    - 12
    - 38
    - 0.239
    - 0.897
  - 
    - 12
    - 39
    - 0.206
    - 0.916
  - 
    - 12
    - 40
    - 0.266
    - 0.918
  - 
    - 12
    - 41
    - 0.325
    - 0.919
  - 
    - 12
    - 42
    - 0.382
    - 0.919
  - 
    - 12
    - 43
    - 0.444
    - 0.921
  - 
    - 12
    - 44
    - 0.438
    - 0.942
  - 
    - 12
    - 45
    - 0.377
    - 0.941
  - 
    - 12
    - 46
    - 0.323
    - 0.939
  - 
    - 12
    - 47
    - 0.259
    - 0.938
  - 
    - 12
    - 48
    - 0.199
    - 0.935
  - 
    - 12
    - 49
    - 0.195
    - 0.957
  - 
    - 13
    - 0
    - 0.466
    - 0.642
  - 
    - 13
    - 1
    - 0.466
    - 0.618
  - 
    - 13
    - 2
    - 0.52
    - 0.619
  - 
    - 13
    - 3
    - 0.566
    - 0.602
  - 
    - 13
    - 4
    - 0.502
    - 0.599
  - 
    - 13
    - 5
    - 0.445
    - 0.6
  - 
    - 13
    - 6
    - 0.451
    - 0.576
  - 
    - 13
    - 7
    - 0.511
    - 0.576
  - 
    - 13
    - 8
    - 0.571
    - 0.578
  - 
    - 13
    - 9
    - 0.543
    - 0.558
  - 
    - 13
    - 10
    - 0.475
    - 0.557
  - 
    - 13
    - 11
    - 0.475
    - 0.533
  - 
    - 13
    - 12
    - 0.55
    - 0.535
  - 
    - 13
    - 13
    - 0.609
    - 0.536
  - 
    - 13
    - 14
    - 0.604
    - 0.56
  - 
    - 13
    - 15
    - 0.63
    - 0.58
  - 
    - 13
    - 16
    - 0.666
    - 0.56
  - 
    - 13
    - 17
    - 0.672
    - 0.538
  - 
    - 13
    - 18
    - 0.674
    - 0.514
  - 
    - 13
    - 19
    - 0.736
    - 0.514
  - 
    - 13
    - 20
    - 0.732
    - 0.54
  - 
    - 13
    - 21
    - 0.73
    - 0.563
  - 
    - 13
    - 22
    - 0.79
    - 0.563
  - 
    - 13
    - 23
    - 0.795
    - 0.537
  - 
    - 13
    - 24
    - 0.8
    - 0.516
  - 
    - 13
    - 25
    - 0.802
    - 0.492
  - 
    - 13
    - 26
    - 0.866
    - 0.494
  - 
    - 13
    - 27
    - 0.861
    - 0.517
  - 
    - 13
    - 28
    - 0.855
    - 0.541
  - 
    - 13
    - 29
    - 0.852
    - 0.563
  - 
    - 13
    - 30
    - 0.816
    - 0.582
  - 
    - 13
    - 31
    - 0.752
    - 0.581
  - 
    - 13
    - 32
    - 0.692
    - 0.58
  - 
    - 13
    - 33
    - 0.686
    - 0.603
  - 
    - 13
    - 34
    - 0.75
    - 0.605
  - 
    - 13
    - 35
    - 0.811
    - 0.606
  - 
    - 13
    - 36
    - 0.868
    - 0.607
  - 
    - 13
    - 37
    - 0.866
    - 0.63
  - 
    - 13
    - 38
    - 0.803
    - 0.628
  - 
    - 13
    - 39
    - 0.74
    - 0.627
  - 
    - 13
    - 40
    - 0.735
    - 0.651
  - 
    - 13
    - 41
    - 0.8
    - 0.652
  - 
    - 13
    - 42
    - 0.866
    - 0.653
  - 
    - 13
    - 43
    - 0.857
    - 0.676
  - 
    - 13
    - 44
    - 0.795
    - 0.675
  - 
    - 13
    - 45
    - 0.734
    - 0.673
  - 
    - 13
    - 46
    - 0.729
    - 0.696
  - 
    - 13
    - 47
    - 0.788
    - 0.698
  - 
    - 13
    - 48
    - 0.852
    - 0.699
  - 
    - 13
    - 49
    - 0.907
    - 0.716
  - 
    - 14
    - 0
    - 0.418
    - 0.533
  - 
    - 14
    - 1
    - 0.42
    - 0.555
  - 
    - 14
    - 2
    - 0.391
    - 0.575
  - 
    - 14
    - 3
    - 0.389
    - 0.598
  - 
    - 14
    - 4
    - 0.411
    - 0.618
  - 
    - 14
    - 5
    - 0.41
    - 0.641
  - 
    - 14
    - 6
    - 0.351
    - 0.639
  - 
    - 14
    - 7
    - 0.286
    - 0.639
  - 
    - 14
    - 8
    - 0.29
    - 0.617
  - 
    - 14
    - 9
    - 0.352
    - 0.616
  - 
    - 14
    - 10
    - 0.323
    - 0.597
  - 
    - 14
    - 11
    - 0.258
    - 0.596
  - 
    - 14
    - 12
    - 0.264
    - 0.572
  - 
    - 14
    - 13
    - 0.327
    - 0.573
  - 
    - 14
    - 14
    - 0.36
    - 0.555
  - 
    - 14
    - 15
    - 0.361
    - 0.531
  - 
    - 14
    - 16
    - 0.3
    - 0.53
  - 
    - 14
    - 17
    - 0.298
    - 0.553
  - 
    - 14
    - 18
    - 0.232
    - 0.553
  - 
    - 14
    - 19
    - 0.239
    - 0.528
  - 
    - 14
    - 20
    - 0.239
    - 0.506
  - 
    - 14
    - 21
    - 0.175
    - 0.502
# [channel,pixel,x,y]
# pixel, relative to the channel
# x,y relative to the letter
